unit uDM;

interface

uses
  SysUtils, Classes, DB, DBTables, Provider, ADODB, DBXpress, FMTBcd,
  SqlExpr;

type
  TDMPrincipal = class(TDataModule)
    ConLOGIN1: TADOConnection;
    datasetAux2: TADODataSet;
    ADODSUsuario: TADODataSet;
    ADODSUsuariousu_nome: TStringField;
    ADODSUsuariousu_senha: TStringField;
    DSUsuario: TDataSource;
    ADODSInvestidor: TADODataSet;
    DSInvestidor: TDataSource;
    ADODSUsuariousu_id: TIntegerField;
    DSAlocacao: TDataSource;
    ADODSAlocacao: TADODataSet;
    ADODSTipInvest: TADODataSet;
    ADODSStatus: TADODataSet;
    ADODSStatuscod_status: TAutoIncField;
    ADODSStatusdsc_status: TStringField;
    ADODSGestor: TADODataSet;
    DSTipInvest: TDataSource;
    DSStatus: TDataSource;
    DSGestor: TDataSource;
    ADODSCarteira: TADODataSet;
    ADODSCarteiraInvestidor: TStringField;
    ADODSCarteiraStatus: TStringField;
    DSCarteira: TDataSource;
    ADODSAtivo: TADODataSet;
    DSAtivo: TDataSource;
    ADODSCaracteristica: TADODataSet;
    DSCaracteristica: TDataSource;
    ADOQTipInvest: TADOQuery;
    dsqTipInvest: TDataSource;
    ADOQAtivo: TADOQuery;
    dsqAtivo: TDataSource;
    ADOQAtivocod_ativo: TAutoIncField;
    ADOQAtivonom_ativo: TStringField;
    ADOQAtivodsc_caracteristicaativo: TStringField;
    ADOQAtivocod_tipoinvestimento: TIntegerField;
    ADOQAtivodat_abertura: TDateTimeField;
    ADOQAtivodat_vencimento: TDateTimeField;
    ADOQAtivocod_gestor: TIntegerField;
    ADOQAtivocod_gestor_1: TAutoIncField;
    ADOQAtivodsc_gestor: TStringField;
    ADOQAtivocto_gestor: TStringField;
    ADOQAtivocod_tipoinvestimento_1: TAutoIncField;
    ADOQAtivodsc_tipoinvestimento: TStringField;
    ADOQAtivocod_caracteristica: TIntegerField;
    ADOQAtivocod_caracteristica_1: TAutoIncField;
    ADOQAtivodsc_caracteristica: TStringField;
    ADOQFechamento: TADOQuery;
    dsFechamento: TDataSource;
    ADOQAlocacoes: TADOQuery;
    dsAlocacoes: TDataSource;
    dsValidaComp: TDataSource;
    ADOQValidaComp: TADOQuery;
    ADOQRentab: TADOQuery;
    dsqRentab: TDataSource;
    ADODSMovimento: TADODataSet;
    DSMovimento: TDataSource;
    ADOQMovto: TADOQuery;
    dsqMovto: TDataSource;
    ADOQMovtocod_investimento: TAutoIncField;
    ADOQMovtocod_ativo: TIntegerField;
    ADOQMovtodsc_investimento: TStringField;
    ADOQMovtovlr_alocado: TBCDField;
    ADOQMovtovlr_atualizado: TBCDField;
    ADOQMovtocod_proprietario: TIntegerField;
    ADOQMovtocod_carteira: TIntegerField;
    ADOQMovtocod_status: TIntegerField;
    ADOQMovtodat_inicio_investimento: TDateField;
    ADOQMovtodat_fim_investimento: TDateField;
    ADOQMovtodat_atualizacao: TDateField;
    ADOQMovtodsc_observacao: TStringField;
    ADOQMovtonro_cotas: TSmallintField;
    ADOQPerformace: TADOQuery;
    dsqPerformace: TDataSource;
    ADOQPerformacedsc_investimento: TStringField;
    ADOQPerformacevlr_alocado: TStringField;
    ADOQPerformacejaneiro: TStringField;
    ADOQPerformacefevereiro: TStringField;
    ADOQPerformacemarco: TStringField;
    ADOQPerformaceabril: TStringField;
    ADOQPerformacemaio: TStringField;
    ADOQPerformacejunho: TStringField;
    ADOQPerformacejulho: TStringField;
    ADOQPerformaceagosto: TStringField;
    ADOQPerformacesetembro: TStringField;
    ADOQPerformaceoutubro: TStringField;
    ADOQPerformacenovembro: TStringField;
    ADOQPerformacedezembro: TStringField;
    ADODSMovimentocod_movimento: TAutoIncField;
    ADODSMovimentocod_ativo: TIntegerField;
    ADODSMovimentocod_carteira: TIntegerField;
    ADODSMovimentotip_movimento: TStringField;
    ADODSMovimentovlr_movimento: TBCDField;
    ADODSMovimentodat_movimento: TDateTimeField;
    ADODSMovimentoAtivo: TStringField;
    ADODSMovimentoCarteira: TStringField;
    ConLOGIN2: TADOConnection;
    ADODataSet1: TADODataSet;
    ADODSInvestidorcod_proprietario: TAutoIncField;
    ADODSInvestidornom_proprietario: TStringField;
    ADODSGestorcod_gestor: TAutoIncField;
    ADODSGestordsc_gestor: TStringField;
    ADODSGestorcto_gestor: TStringField;
    ADODSCaracteristicacod_caracteristica: TAutoIncField;
    ADODSCaracteristicadsc_caracteristica: TStringField;
    ADOQTipInvestcod_tipoinvestimento: TAutoIncField;
    ADOQTipInvestdsc_tipoinvestimento: TStringField;
    ADOQTipInvestcod_caracteristica: TIntegerField;
    ADOQTipInvestdsc_caracteristica: TStringField;
    ADOQTipInvestdsc_caracteristica_1: TStringField;
    ADODSCarteiracod_carteira: TAutoIncField;
    ADODSCarteiranom_carteira: TStringField;
    ADODSCarteiradat_criacao: TDateTimeField;
    ADODSCarteiracod_proprietario: TIntegerField;
    ADODSCarteiracod_status: TIntegerField;
    ADODSAtivocod_ativo: TAutoIncField;
    ADODSAtivonom_ativo: TStringField;
    ADODSAtivocod_caracteristica: TIntegerField;
    ADODSAtivodsc_caracteristicaativo: TStringField;
    ADODSAtivocod_tipoinvestimento: TIntegerField;
    ADODSAtivodat_abertura: TDateTimeField;
    ADODSAtivodat_vencimento: TDateTimeField;
    ADODSAtivocod_gestor: TIntegerField;
    ADODSTipInvestcod_tipoinvestimento: TAutoIncField;
    ADODSTipInvestdsc_tipoinvestimento: TStringField;
    ADODSTipInvestcod_caracteristica: TIntegerField;
    ADODSTipInvestdsc_caracteristica: TStringField;
    ADODSMovimentovlr_unitario: TBCDField;
    ADOQPesqCarteira: TADOQuery;
    DSPesqCarteira: TDataSource;
    ADOQPesqCarteiracod_carteira: TAutoIncField;
    ADOQPesqCarteiranom_carteira: TStringField;
    ADOQPesqCarteiradat_criacao: TDateTimeField;
    ADOQPesqCarteiracod_proprietario: TIntegerField;
    ADOQPesqCarteiracod_status: TIntegerField;
    ADODSMovimentovlr_outras_despesas: TBCDField;
    ADODSMovimentocat_movimento: TStringField;
    ADODSAlocacaocod_investimento: TAutoIncField;
    ADODSAlocacaodsc_investimento: TStringField;
    ADODSAlocacaocod_proprietario: TIntegerField;
    ADODSAlocacaocod_carteira: TIntegerField;
    ADODSAlocacaocod_status: TIntegerField;
    ADODSAlocacaodat_abertura: TDateTimeField;
    ADODSAlocacaodat_vencimento: TDateTimeField;
    ADODSAlocacaocod_ativo: TIntegerField;
    ADODSAlocacaovlr_alocado: TBCDField;
    ADODSAlocacaovlr_atualizado: TBCDField;
    ADODSAlocacaodat_atualizacao: TDateTimeField;
    ADODSAlocacaodsc_observacao: TStringField;
    ADODSAlocacaonro_cotas: TBCDField;
    ADODSMovimentoqtd_cotas: TBCDField;
    ADODSAlocacaoInvestidor: TStringField;
    ADODSAlocacaoSituacao: TStringField;
    ADODSAlocacaocod_tipoinvestimento: TIntegerField;
    ADODSAlocacaoTipo: TStringField;
    ADODSTpProvento: TADODataSet;
    DSTpProvento: TDataSource;
    ADODSTpProventocod_tipprovento: TAutoIncField;
    ADODSTpProventodsc_tipprovento: TStringField;
    ADODSTpProventoobs_tipprovento: TStringField;
    ADODSProvento: TADODataSet;
    DSProvento: TDataSource;
    ADODSProventocod_provento: TAutoIncField;
    ADODSProventocod_tipprovento: TIntegerField;
    ADODSProventocompetencia: TDateTimeField;
    ADODSProventocod_ativo: TIntegerField;
    ADODSProventodat_pagamento: TDateTimeField;
    ADODSProventovlr_por_cota_acao: TBCDField;
    ADODSProventoqtd_cotas: TBCDField;
    ADODSProventovlr_total: TBCDField;
    ADODSProventodsc_observacao: TStringField;
    ADODSProventocod_carteira: TIntegerField;
    ADODSProventoAtivo: TStringField;
    ADODSProventoTpProv: TStringField;
    ADODSSitMeta: TADODataSet;
    DSSitMeta: TDataSource;
    ADODSSitMetacod_sitmeta: TAutoIncField;
    ADODSSitMetadsc_sitmeta: TStringField;
    ADODSSitMetadsc_observacao: TStringField;
    ADODSMeta: TADODataSet;
    DSMeta: TDataSource;
    ADODSMetacod_meta: TAutoIncField;
    ADODSMetadsc_meta: TStringField;
    ADODSMetadat_inicial: TDateTimeField;
    ADODSMetadat_final: TDateTimeField;
    ADODSMetavlr_inicial: TBCDField;
    ADODSMetavlr_final: TBCDField;
    ADODSMetavlr_atual: TBCDField;
    ADODSMetacod_sitmeta: TIntegerField;
    ADODSMetadsc_observacao: TStringField;
    ADODSMetadat_atualizacao: TDateTimeField;
    ADODSProventoCarteira: TStringField;
    ADODSMetaSituacao: TStringField;
    ADODSMetapct_atingido: TBCDField;
    ADOQProventos: TADOQuery;
    dsqProventos: TDataSource;
    ADOQProventosvalor_total: TBCDField;
    ADODSCambio: TADODataSet;
    DSCambio: TDataSource;
    ADODSCambiocod_cambio: TAutoIncField;
    ADODSCambiodat_solicitacao: TDateTimeField;
    ADODSCambiodat_cambio: TDateTimeField;
    ADODSCambiocod_carteira: TIntegerField;
    ADODSCambiocod_proprietario: TIntegerField;
    ADODSCambiovlr_aporte_br: TBCDField;
    ADODSCambiovlr_aporte_us: TBCDField;
    ADODSCambiovlr_taxas: TBCDField;
    ADODSCambiovlr_final_br: TBCDField;
    ADODSCambiovlr_cotacao_dolar: TBCDField;
    ADODSCambiodsc_observacao: TStringField;
    ADODSCambiodat_cadastro: TDateTimeField;
    ADODSCambiocod_status: TIntegerField;
    ADODSCambioProprietario: TStringField;
    ADODSCambioCarteira: TStringField;
    ADODSCambioSituacao: TStringField;
    ADOQAlocacoesdsc_investimento: TStringField;
    ADOQAlocacoesdsc_tipoinvestimento: TStringField;
    ADOQAlocacoesdsc_observacao: TStringField;
    ADOQAlocacoesnom_carteira: TStringField;
    ADOQAlocacoesnom_proprietario: TStringField;
    ADOQAlocacoesvlr_alocado: TWideStringField;
    ADOQAlocacoesvlr_atualizado: TWideStringField;
    ADOQAlocacoesdat_abertura: TDateTimeField;
    ADOQAlocacoesdat_vencimento: TDateTimeField;
    ADOQAlocacoesdat_atualizacao: TDateTimeField;
    ADOQAlocacoesnro_cotas: TBCDField;
    ADOQAlocacoesdsc_status: TStringField;
    ADOQRentabdsc_investimento: TStringField;
    ADOQRentabdsc_tipoinvestimento: TStringField;
    ADOQRentabdsc_observacao: TStringField;
    ADOQRentabnom_carteira: TStringField;
    ADOQRentabvlr_alocado: TWideStringField;
    ADOQRentabvlr_atualizado: TWideStringField;
    ADOQRentabvlr_ret_liq: TWideStringField;
    ADOQRentabdsc_status: TStringField;
    ADOQRentabcotas: TBCDField;
    ADODSAlocacaoCarteira: TStringField;
    ADOQProventosAno: TADOQuery;
    dsProventosAno: TDataSource;
    ADOQProventosAnonom_ativo: TStringField;
    ADOQProventosAnopreco_medio: TWideStringField;
    ADOQProventosAnojaneiro: TWideStringField;
    ADOQProventosAnofevereiro: TWideStringField;
    ADOQProventosAnomarco: TWideStringField;
    ADOQProventosAnoabril: TWideStringField;
    ADOQProventosAnomaio: TWideStringField;
    ADOQProventosAnojunho: TWideStringField;
    ADOQProventosAnojulho: TWideStringField;
    ADOQProventosAnoagosto: TWideStringField;
    ADOQProventosAnosetembro: TWideStringField;
    ADOQProventosAnooutubro: TWideStringField;
    ADOQProventosAnonovembro: TWideStringField;
    ADOQProventosAnodezembro: TWideStringField;
    ADOQProventosAnoval_atualizado: TWideStringField;
    ADOQProventosAnonro_cotas: TWideStringField;
    ADOQTotalInvestido: TADOQuery;
    DSQTotalInvestido: TDataSource;
    ADOQTotalInvestidoval_investido: TWideStringField;
    ADOQCambio: TADOQuery;
    dsqCambio: TDataSource;
    ADOQCambiodat_solicitacao: TDateTimeField;
    ADOQCambiodat_cambio: TDateTimeField;
    ADOQCambionom_carteira: TStringField;
    ADOQCambionom_proprietario: TStringField;
    ADOQCambiovlr_aporte_br: TWideStringField;
    ADOQCambiovlr_taxas: TWideStringField;
    ADOQCambiovlr_final_br: TWideStringField;
    ADOQCambiovlr_cotacao_dolar: TStringField;
    ADOQCambiodat_cadastro: TDateTimeField;
    ADOQCambiosituacao: TStringField;
    ADOQCambiodsc_observacao: TStringField;
    ADOQCambiovlr_aporte_us: TBCDField;
    ADOQProventosAnototal: TWideStringField;
    ADOQMovimentos: TADOQuery;
    dsMovimentos: TDataSource;
    ADOQMovimentosnom_carteira: TStringField;
    ADOQMovimentosdat_movimento: TWideStringField;
    ADOQMovimentosnom_ativo: TStringField;
    ADOQMovimentostip_movimento: TStringField;
    ADOQMovimentosqtd_cotas: TBCDField;
    ADOQMovimentosvlr_unitario: TBCDField;
    ADOQMovimentosvlr_outras_despesas: TBCDField;
    ADOQMovimentosvlr_movimento: TBCDField;
    ADOQMovimentoscat_movimento: TStringField;
    ADOQMovimentosnom_proprietario: TStringField;
    ADOQMovimentosdsc_tipoinvestimento: TStringField;
    ADOQPesqStatus: TADOQuery;
    DSPesqStatus: TDataSource;
    ADOQPesqStatuscod_status: TAutoIncField;
    ADOQPesqStatusdsc_status: TStringField;
    ADODSAnuncioProvento: TADODataSet;
    DSAnuncioProvento: TDataSource;
    ADODSAnuncioProventocod_prev_proventos: TAutoIncField;
    ADODSAnuncioProventodat_anuncio: TDateTimeField;
    ADODSAnuncioProventocod_ativo: TIntegerField;
    ADODSAnuncioProventodat_com: TDateTimeField;
    ADODSAnuncioProventodat_pagamento: TDateTimeField;
    ADODSAnuncioProventocod_tipprovento: TIntegerField;
    ADODSAnuncioProventovlr_bruto: TBCDField;
    ADODSAnuncioProventovlr_ir: TBCDField;
    ADODSAnuncioProventovlr_liquido: TBCDField;
    ADODSAnuncioProventocod_status: TIntegerField;
    ADODSAnuncioProventoAtivo: TStringField;
    ADODSAnuncioProventoTpProv: TStringField;
    ADODSAnuncioProventoSituacao: TStringField;
    ADODSAnuncioProventopct_ir: TBCDField;
    ADOQAnunciosProventos: TADOQuery;
    dsAnunciosProventos: TDataSource;
    ADOQAnunciosProventosdt_pagamento: TWideStringField;
    ADOQAnunciosProventosdt_com: TWideStringField;
    ADOQAnunciosProventoscod_ativo: TIntegerField;
    ADOQAnunciosProventosnom_ativo: TStringField;
    ADOQAnunciosProventoscod_tipprovento: TIntegerField;
    ADOQAnunciosProventosdsc_tipprovento: TStringField;
    ADOQAnunciosProventosvlr_bruto: TBCDField;
    ADOQAnunciosProventospct_ir: TBCDField;
    ADOQAnunciosProventosvlr_ir: TBCDField;
    ADOQAnunciosProventosvlr_liquido: TBCDField;
    ADOQAnunciosProventoscod_status: TIntegerField;
    ADOQAnunciosProventosdsc_status: TStringField;
    ADOQAnunciosProventosnom_proprietario: TStringField;
    ADOQAnunciosProventosvalor_a_receber: TBCDField;
    ADOQAnunciosProventosnro_cotas: TBCDField;
    ADOQConProventosAno: TADOQuery;
    dsConProventosAno: TDataSource;
    ADOQConProventosAnonom_ativo: TStringField;
    ADOQConProventosAnoval_atualizado: TWideStringField;
    ADOQConProventosAnonro_cotas: TWideStringField;
    ADOQConProventosAnopreco_medio: TWideStringField;
    ADOQConProventosAnojaneiro: TWideStringField;
    ADOQConProventosAnofevereiro: TWideStringField;
    ADOQConProventosAnomarco: TWideStringField;
    ADOQConProventosAnoabril: TWideStringField;
    ADOQConProventosAnomaio: TWideStringField;
    ADOQConProventosAnojunho: TWideStringField;
    ADOQConProventosAnojulho: TWideStringField;
    ADOQConProventosAnoagosto: TWideStringField;
    ADOQConProventosAnosetembro: TWideStringField;
    ADOQConProventosAnooutubro: TWideStringField;
    ADOQConProventosAnonovembro: TWideStringField;
    ADOQConProventosAnodezembro: TWideStringField;
    ADOQConProventosAnototal: TWideStringField;
    ADOQConProventosAnomedia: TWideStringField;
    ADOQConAux1: TADOQuery;
    ADOQConAux1val_atualizado: TWideStringField;
    ADOQConAux1nro_cotas: TWideStringField;
    ADOQConAux1janeiro: TWideStringField;
    ADOQConAux1fevereiro: TWideStringField;
    ADOQConAux1marco: TWideStringField;
    ADOQConAux1abril: TWideStringField;
    ADOQConAux1maio: TWideStringField;
    ADOQConAux1junho: TWideStringField;
    ADOQConAux1julho: TWideStringField;
    ADOQConAux1agosto: TWideStringField;
    ADOQConAux1setembro: TWideStringField;
    ADOQConAux1outubro: TWideStringField;
    ADOQConAux1novembro: TWideStringField;
    ADOQConAux1dezembro: TWideStringField;
    ADOQConAux1total: TWideStringField;
    ADOQConAux1media: TWideStringField;
    ADOQConAux1preco_medio: TWideStringField;
    procedure ADOQAtivodat_aberturaSetText(Sender: TField;
      const Text: String);
    procedure ADOQAtivodat_vencimentoSetText(Sender: TField;
      const Text: String);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DMPrincipal: TDMPrincipal;

implementation

{$R *.dfm}

procedure TDMPrincipal.ADOQAtivodat_aberturaSetText(Sender: TField;
  const Text: String);
begin
  if Text = '  /  /    ' then
    Sender.AsString := ''
  else
    try
      Sender.AsString := DateToStr(StrToDate(Text));
    except
      Sender.AsString := '';
    end;  
end;

procedure TDMPrincipal.ADOQAtivodat_vencimentoSetText(Sender: TField;
  const Text: String);
begin
  if Text = '  /  /    ' then
    Sender.AsString := ''
  else
    try
      Sender.AsString := DateToStr(StrToDate(Text));
    except
      Sender.AsString := '';
    end;  
end;

end.
